export const DATA_UUID_KEY = 'data-uuid___'
export const DATA_LAYOUT_UUID_KEY = 'data-layout-uuid___'
export const DATA_LAYOUT_ITEM_UUID_KEY = 'data-layout-item-uuid___'
export let VARS_PAGE_MODEL_NAME = 'play-events-model'
export let APP_STORE_NAME = 'home-index-store'
